config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :visitors
  devise_for :models
  root 'visitors#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/rhino.rb
class Rhino < ApplicationRecord
end

app/models/visitor.rb
class Visitor < ApplicationRecord
    validates :date, presence: true
    validates :arrival, presence: true
    validates :name, presence: true
    validates :company, presence: true
    validates :eps, presence: true
    validates :arl, presence: true
    validates :rh, presence: true
    validates :alergy, presence: true
    validates :output, presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/form_controller.rb
class FormController < ApplicationController
  def index
  end
end

app/controllers/rhino_controller.rb
class RhinoController < ApplicationController
    def index
        @rhinos = Rhino.all
    end
    def new 
        @rhino = Rhino.new
    end 
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: [:show, :edit, :update, :destroy]

  # GET /visitors
  # GET /visitors.json
  def index
    @visitors = Visitor.paginate(page: params[:page], per_page: 10).all
  
  end

  # GET /visitors/1
  # GET /visitors/1.json
  def show
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors
  # POST /visitors.json
  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to @visitor, notice: 'Ha completado con éxito todas las preguntas. Gracias por usar el sistema de control de visitantes de Merak Engineers' }
        format.json { render :show, status: :created, location: @visitor }
      else
        format.html { render :new }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1
  # PATCH/PUT /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to @visitor, notice: 'Editado correctamente.' }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.json
  def destroy
    @visitor.destroy
    respond_to do |format|
      format.html { redirect_to visitors_url, notice: 'Eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visitor_params
      params.require(:visitor).permit(:date, :arrival, :name, :company, :eps, :arl, :rh, :alergy, :phone, :injury, :output)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper
end

app/helpers/rhino_helper.rb
module RhinoHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/form/index.html.erb
<div class="container">
<div class="row">
    <div class="col-md-8 order-md-1">
      <h4 class="mb-3">Billing address</h4>
      <form class="needs-validation" novalidate="">
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="firstName">First name</label>
            <input type="text" class="form-control" id="firstName" placeholder="" value="" required="">
            <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="lastName">Last name</label>
            <input type="text" class="form-control" id="lastName" placeholder="" value="" required="">
            <div class="invalid-feedback">
              Valid last name is required.
            </div>
          </div>
        </div>

        <div class="mb-3">
          <label for="username">Username</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">@</span>
            </div>
            <input type="text" class="form-control" id="username" placeholder="Username" required="">
            <div class="invalid-feedback" style="width: 100%;">
              Your username is required.
            </div>
          </div>
        </div>

        <div class="mb-3">
          <label for="email">Email <span class="text-muted">(Optional)</span></label>
          <input type="email" class="form-control" id="email" placeholder="you@example.com">
          <div class="invalid-feedback">
            Please enter a valid email address for shipping updates.
          </div>
        </div>

        <div class="mb-3">
          <label for="address">Address</label>
          <input type="text" class="form-control" id="address" placeholder="1234 Main St" required="">
          <div class="invalid-feedback">
            Please enter your shipping address.
          </div>
        </div>

        <div class="mb-3">
          <label for="address2">Address 2 <span class="text-muted">(Optional)</span></label>
          <input type="text" class="form-control" id="address2" placeholder="Apartment or suite">
        </div>

        <div class="row">
          <div class="col-md-5 mb-3">
            <label for="country">Country</label>
            <select class="custom-select d-block w-100" id="country" required="">
              <option value="">Choose...</option>
              <option>United States</option>
            </select>
            <div class="invalid-feedback">
              Please select a valid country.
            </div>
          </div>
          <div class="col-md-4 mb-3">
            <label for="state">State</label>
            <select class="custom-select d-block w-100" id="state" required="">
              <option value="">Choose...</option>
              <option>California</option>
            </select>
            <div class="invalid-feedback">
              Please provide a valid state.
            </div>
          </div>
          <div class="col-md-3 mb-3">
            <label for="zip">Zip</label>
            <input type="text" class="form-control" id="zip" placeholder="" required="">
            <div class="invalid-feedback">
              Zip code required.
            </div>
          </div>
        </div>
        <hr class="mb-4">
        <div class="custom-control custom-checkbox">
          <input type="checkbox" class="custom-control-input" id="same-address">
          <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
        </div>
        <div class="custom-control custom-checkbox">
          <input type="checkbox" class="custom-control-input" id="save-info">
          <label class="custom-control-label" for="save-info">Save this information for next time</label>
        </div>
        <hr class="mb-4">

        <h4 class="mb-3">Payment</h4>

        <div class="d-block my-3">
          <div class="custom-control custom-radio">
            <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" checked="" required="">
            <label class="custom-control-label" for="credit">Credit card</label>
          </div>
          <div class="custom-control custom-radio">
            <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" required="">
            <label class="custom-control-label" for="debit">Debit card</label>
          </div>
          <div class="custom-control custom-radio">
            <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required="">
            <label class="custom-control-label" for="paypal">PayPal</label>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="cc-name">Name on card</label>
            <input type="text" class="form-control" id="cc-name" placeholder="" required="">
            <small class="text-muted">Full name as displayed on card</small>
            <div class="invalid-feedback">
              Name on card is required
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="cc-number">Credit card number</label>
            <input type="text" class="form-control" id="cc-number" placeholder="" required="">
            <div class="invalid-feedback">
              Credit card number is required
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-3 mb-3">
            <label for="cc-expiration">Expiration</label>
            <input type="text" class="form-control" id="cc-expiration" placeholder="" required="">
            <div class="invalid-feedback">
              Expiration date required
            </div>
          </div>
          <div class="col-md-3 mb-3">
            <label for="cc-cvv">CVV</label>
            <input type="text" class="form-control" id="cc-cvv" placeholder="" required="">
            <div class="invalid-feedback">
              Security code required
            </div>
          </div>
        </div>
        <hr class="mb-4">
        <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>
      </form>
    </div>
  </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rhino - Merak</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <link rel="manifest" href="/manifest.json">
  </head>

  <body>
    <%= yield %>
  </body>

  <footer class="my-5 pt-5 text-muted text-center text-small" style="background: #eeeeee; ">
        <p class="mb-1">Desarrollado por <a href="http://www.merakengineers.com">Merak Engineers</a></p>
      </footer>
</html>

app/views/rhino/index.html.erb
<%= @rhinos.inspect %>

app/views/rhino/new.html.erb
<%= form_with model: @rhino, class: "nifty_form" do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :body, size: "60x12" %>
  <%= f.submit "Create" %>
<% end %>

app/views/visitors/_form.html.erb
<div id="container">
  <div id="row">
    <div class="col-sm-12 col-md-12 col-xs-12 " style="background: #eeeeee; ">
    <div class="card" style=" width: 600px;max-width: 100%;border: 2px solid #eeeeee;background: #eeeeee;margin:0 auto;color: steelblue;border-radius: 20px;"> 
      <div class="logo"><img src="<%= asset_path 'logo-min.png' %>" style="height: 80px;"><h4 class="mb-12">Control de visitantes</h4></div>
        <%= form_with(model: visitor, local: true) do |form| %>
            <% if visitor.errors.any? %>
            <div class="alert alert-danger">
              <% visitor.errors.full_messages.each do |message| %>
                
                    <%= message %>,
                    <% end %>
                </div>
            <% end %>
            <div class="field ">
              <%= form.label "Fecha" %>
              <%= form.date_field :date,class: "form-control form-control-sm" %>
            </div>

            <div class="field">
              <%= form.label "Hora de llegada" %>
              <%= form.time_field :arrival,class: "form-control form-control-sm"  %>
            </div>

            <div class="field">
              <%= form.label "Nombre" %>
              <%= form.text_field :name, class:"form-control form-control-sm"%>
            </div>

            <div class="field">
              <%= form.label "Compañía" %>
              <%= form.text_field :company,class:"form-control form-control-sm"%>
            </div>

            <div class="field">
              <%= form.label "eps" %>
              <%= form.text_field :eps,class:"form-control form-control-sm" %>
            </div>

            <div class="field">
              <%= form.label "arl" %>
              <%= form.text_field :arl,class:"form-control form-control-sm" %>
            </div>

            <div class="field">
              <%= form.label "rh" %>
              <%= form.text_field :rh,class:"form-control form-control-sm"%>
            </div>

            <div class="field">
              <%= form.label "Alergias" %>
              <%= form.text_field :alergy,class:"form-control form-control-sm" %>
            </div>

            <div class="field">
              <%= form.label "Número EN CASO DE EMERGENCIA" %>
              <%= form.text_field :phone,class:"form-control form-control-sm" %>
            </div>

             <div class="form-check form-check-inline">
              <%= form.check_box :injury,class:"form-check-input" %>
              <label class="form-check-label" for="visitor_injury">¿Sufrió lesión en la visita?</label>
          </div>

            <div class="field">
              <%= form.label "Hora de salida" %>
              <%= form.time_field :output,class: "form-control" %>
            </div>

            <div class="actions " style="padding: 20px;text-align: center;">
              <%= form.submit 'Guardar', :class => 'btn btn-primary btn-lg btn-block' %>
            </div>
      <% end %>
    </div>
    </div>
  </div>
 </div> 
  </div> 
  

app/views/visitors/edit.html.erb
<%= render 'form', visitor: @visitor %>

<%= link_to 'Visitantes', @visitor %> |
<%= link_to 'Atras', visitors_path %>

app/views/visitors/index.html.erb
<div class="container" style=" 
    /* background: gray; */
    background: #eeeeee;
    color: steelblue;
    padding: 20px;"
>
    <p id="notice"><%= notice %></p>
    <div class="logo"><img src="<%= asset_path 'logo-min.png' %>" style="height: 80px;"><h4 class="mb-12">Control de visitantes</h4></div>
      <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>Fecha</th>
                  <th>Hora de llegada</th>
                  <th>Nombre</th>
                  <th>Compañía</th>
                  <th>Eps</th>
                  <th>Arl</th>
                  <th>Rh</th>
                  <th>Alergias</th>
                  <th>Número en caso de emergencia </th>
                  <th>¿Sufrió lesión en la visita?</th>
                  <th>Hora de salida</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                <% @visitors.each do |visitor| %>
                  <tr>
                    <td><%= visitor.date %></td>
                    <td><%= visitor.arrival.strftime("%I:%M %p")  %></td>
                    <td><%= visitor.name %></td>
                    <td><%= visitor.company %></td>
                    <td><%= visitor.eps %></td>
                    <td><%= visitor.arl %></td>
                    <td><%= visitor.rh %></td>
                    <td><%= visitor.alergy %></td>
                    <td><%= visitor.phone %></td>
                    <td><%= visitor.injury ? "Si" : "no" %></td>
                    <td><%= visitor.output.strftime("%I:%M %p") %></td>
                    <td><%= link_to 'Mostrar', visitor %></td>
                    <td><%= link_to 'Editar', edit_visitor_path(visitor) %></td>
                    <td><%= link_to 'Eliminar', visitor, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
      <%= will_paginate @visitors %>
      <br>
    </div>

<%= link_to 'Nuevo visitante', new_visitor_path %>
<div class="logo"><h4 class="mb-12">Estadisticas</h4></div>
  <div class="row" style="text-align:center;">
    <div class=" col-sm-6 col-xs-12">
        <p class="testadisticas">Cantidad de personas inscritas por día</p>
        <%= line_chart Visitor.group_by_day(:date).count %>
    </div>
    <div class=" col-sm-6 col-xs-12">
        <p class="testadisticas">Cantidad de personas inscritas por hora</p>
        <%= line_chart Visitor.group_by_hour(:arrival).count %> 
    </div>
  </div>
<div class="row" style="text-align:center; padding-top:10px;">
    <div class=" col-sm-6 col-xs-12">
        <p class="testadisticas">Cantidad de personas con alergias positivas</p>
        <%= pie_chart Visitor.group(:alergy).count %>
    </div>
    <div class=" col-sm-6 col-xs-12">
          <p class="testadisticas">Cantidad de personas lesionadas</p>
          <%= pie_chart Visitor.group(:injury).count %>
    </div>
  </div>




</div>

app/views/visitors/new.html.erb
<%= render 'form', visitor: @visitor %>

 <%#= link_to 'Atras', visitors_path %>

app/views/visitors/show.html.erb
<div class="card" style=" width: 600px;max-width: 100%;border: 2px solid #eeeeee;background: #eeeeee;margin:0 auto;padding: 40px;"> 
<div class="logo"><img src="<%= asset_path 'logo-min.png' %>" style="height: 80px;"><h4 class="mb-12">Control de visitantes</h4></div>
<p id="notice"><%= notice %></p>
<p>
  <strong class="stellblue">Fecha:</strong>
  <%= @visitor.date %>
</p>

<p>
  <strong class="stellblue">Hora de llegada:</strong>
  <%= @visitor.arrival.strftime("%I:%M %p") %>
</p>

<p>
  <strong class="stellblue">Nombre:</strong>
  <%= @visitor.name %>
</p>

<p>
  <strong class="stellblue">Compañía:</strong>
  <%= @visitor.company %>
</p>

<p>
  <strong class="stellblue">Eps:</strong>
  <%= @visitor.eps %>
</p>

<p>
  <strong class="stellblue">Arl:</strong>
  <%= @visitor.arl %>
</p>

<p>
  <strong class="stellblue">Rh:</strong>
  <%= @visitor.rh %>
</p>

<p>
  <strong class="stellblue">Alergias:</strong>
  <%= @visitor.alergy %>
</p>

<p>
  <strong class="stellblue">Número en caso de emergencia:</strong>
  <%= @visitor.phone %>
</p>

<p>
  <strong class="stellblue">¿Sufrió lesión en la visita?:</strong>
  <%= @visitor.injury ? "Si" : "no" %>
</p>

<p>
  <strong class="stellblue">Hora de salida:</strong>
  <%= @visitor.output.strftime("%I:%M %p") %>
</p>

</div>